/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as VigilRouteImport } from './routes/vigil'
import { Route as SystemsIndexRouteImport } from './routes/systems.index'
import { Route as SystemsIdRouteImport } from './routes/systems.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const VigilRoute = VigilRouteImport.update({
  id: '/vigil',
  path: '/vigil',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIdRoute = SystemsIdRouteImport.update({
  id: '/systems/$id',
  path: '/systems/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/company': typeof CompanyRoute
  '/vigil': typeof VigilRoute
  '/systems/$id': typeof SystemsIdRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/company': typeof CompanyRoute
  '/vigil': typeof VigilRoute
  '/systems/$id': typeof SystemsIdRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/company': typeof CompanyRoute
  '/vigil': typeof VigilRoute
  '/systems/$id': typeof SystemsIdRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analysis' | '/company' | '/vigil' | '/systems/$id' | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis' | '/company' | '/vigil' | '/systems/$id' | '/systems'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/company'
    | '/vigil'
    | '/systems/$id'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CompanyRoute: typeof CompanyRoute
  VigilRoute: typeof VigilRoute
  SystemsIdRoute: typeof SystemsIdRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vigil': {
      id: '/vigil'
      path: '/vigil'
      fullPath: '/vigil'
      preLoaderRoute: typeof VigilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$id': {
      id: '/systems/$id'
      path: '/systems/$id'
      fullPath: '/systems/$id'
      preLoaderRoute: typeof SystemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CompanyRoute: CompanyRoute,
  VigilRoute: VigilRoute,
  SystemsIdRoute: SystemsIdRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
